## use this script to do some QCs on the peaks generated by MACS2
## in particular: plot distribution peak szes; number peaks per binned width
## do this for both species

library(data.table)
library(magrittr)
library(dplyr)
library(ggplot2)
library(ggpubr)

setwd('/data/projects/punim0595/dvespasiani/Human_Chimpanzee_iPSCs_chromatin_accessibility/post_processing_analyses')

scripts_dir <- './scripts/'
source(paste(scripts_dir,'utils.R',sep=''))

peakdir <- paste('../',genome,'/output/PeakCalling/Files',sep='')
outplot_dir <- create_dir(plot_dir,'atac_seq_qc')

peak_files <- list.files(peakdir,full.names=T, recursive=F,pattern="^H.*narrowPeak$|C.*narrowPeak$")

peaks <- lapply(peak_files,function(x)
    x<-fread(x,sep='\t',header=F,select=c(1:3),col.names=range_keys)[
            ,width:=end-start
        ]
)
names(peaks) = samples_names
peaks <- Map(mutate,peaks,samples=samples_names)%>%rbindlist()

peaks <- peaks[,rounded_width:=plyr::round_any(width, 100)] 

pdf(paste(outplot_dir,'distribution_peak_sizes.pdf',sep=''),width=15,height=7)
ggplot(peaks,aes(x=rounded_width,fill=samples))+
    geom_bar()+
    facet_wrap(samples~.,scale='free')+
    ylab('Number of peaks')+ xlab('')+
    theme(legend.position='none')
dev.off()
